### ISSUE TITLE
Mendix 9.12.2 Month Auto Switching

### ISSUE THREAD

**Issue by nrm5** [bsgriggs/mendix-dropdown-date-picker#2] opened 2022-08-31 15:38 UTC
I found a bug when using mendix 9.12.2
The date picker drop down increments the month when changing day or year with the following selections:
Feb - Mar
Apr - May
Jun - Jul
Sept - Oct
Nov - Dec

**Comment by bsgriggs** [comment] 2022-09-21 19:34
Hi, are you still experiencing this issue? I'm having some trouble reproducing it with my test project [here](https://widgettesting105-sandbox.mxapps.io/p/dropdown-date-picker)

**Comment by bsgriggs** [comment] 2022-10-31 20:10
This issue has been resolved with the latest release on the [Mendix Marketplace](https://marketplace.mendix.com/link/component/119971) (v1.3). 

The issue was the order of the setDate functions. new Date() -> setYear() -> setMonth() -> setDate() would have the added effect of incrementing the month because the selected month does not have 31 days. For example, selecting February would try to set Feb 31st since the date function isn't until after the month function, and the browser would automatically adjust Feb 31st to Mar 3rd. The fix is to reverse the order of the date functions.

**Closed as completed by bsgriggs** 2022-10-31 20:10 UTC
Labels: bug
